"""add personal info and security question

Revision ID: 17ec3a2c91bd
Revises: f2b542393168
Create Date: 2026-06-06 00:24:23.555957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ec3a2c91bd'
down_revision = 'f2b542393168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer_hash', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('security_answer_hash')
        batch_op.drop_column('security_question')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('dob')
        batch_op.drop_column('address')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('dob')
        batch_op.drop_column('address')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('dob')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
