"""add phone numbers

Revision ID: f2b542393168
Revises: b3c1d2e4f5a6
Create Date: 2026-06-05 23:33:17.649738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b542393168'
down_revision = 'b3c1d2e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('secondary_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=40), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('secondary_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=40), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('secondary_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('guardian_phone')
        batch_op.drop_column('secondary_phone')
        batch_op.drop_column('primary_phone')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('guardian_phone')
        batch_op.drop_column('secondary_phone')
        batch_op.drop_column('primary_phone')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_column('guardian_phone')
        batch_op.drop_column('secondary_phone')
        batch_op.drop_column('primary_phone')

    # ### end Alembic commands ###
